[tool.poetry]
name = "riparias-early-warning-webapp"
version = "0.1.0"
description = ""
authors = ["Nicolas Noé <nicolas.noe@inbo.be>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
psycopg2-binary = "^2.9.1"
requests = "^2.26.0"
gbif-blocking-occurrence-download = "^0.1.0"
mypy = "^0.910"
django-stubs = "^1.8.0"
python-dwca-reader = "^0.15.0"

[tool.poetry.dev-dependencies]
black = "^21.8b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
